services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: everythingsafety_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      - DEBUG=False
      - DATABASE_NAME=everythingsafety_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs

volumes:
  postgres_data:
