# Generated by Django 5.2.5 on 2025-08-15 10:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_discount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_tax',
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.register'),
        ),
        migrations.AddField(
            model_name='payment',
            name='register_open_sequence_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='retailer_payment_type_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='accounts_transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='complete_open_sequence_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sale',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='has_unsynced_on_account_payments',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='return_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='short_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='source',
            field=models.CharField(choices=[('USER', 'User'), ('API', 'API'), ('IMPORT', 'Import'), ('ECOM', 'E-Commerce')], default='USER', max_length=32),
        ),
        migrations.AddField(
            model_name='sale',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='state',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('closed', 'Closed'), ('parked', 'Parked')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='version',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='gift_card_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='loyalty_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='return_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='core.user'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tax'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='total_discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='total_loyalty_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_loyalty_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('VOIDED', 'Voided'), ('ONACCOUNT', 'On Account'), ('LAYAWAY', 'Layaway'), ('CLOSED', 'Closed'), ('SAVED', 'Saved')], default='COMPLETED', max_length=16),
        ),
        migrations.CreateModel(
            name='EcomCustomCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
                ('tax_amount', models.FloatField(default=0.0)),
                ('amount_incl', models.FloatField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecom_charges', to='core.sale')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_id', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=255)),
                ('version', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_apps', to='core.sale')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentExternalAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=128)),
                ('card_last_four_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=64, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_attributes', to='core.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSurcharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='core.payment')),
            ],
        ),
        migrations.CreateModel(
            name='SaleAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_adjustments', to='core.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItemPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.FloatField()),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promotion')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_promotions', to='core.saleitem')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItemSurcharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_surcharges', to='core.saleitem')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItemTaxComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_id', models.UUIDField()),
                ('total_tax', models.FloatField()),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_components', to='core.saleitem')),
            ],
        ),
        migrations.CreateModel(
            name='SaleTax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_taxes', to='core.sale')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tax')),
            ],
        ),
        migrations.CreateModel(
            name='SaleAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute', models.CharField(max_length=128)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_attributes', to='core.sale')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sale', 'attribute'), name='uq_sale_attribute')],
            },
        ),
    ]
